name: 'Turbo Changed'
description: 'A Github Action making it easy to check if a local workspace changed using Turborepo.'
author: 'Trampoline'
branding:
  icon: git-branch
  color: green
inputs:
  workspace:
    required: true
    description: 'The workspace name we are interested in.'
  from:
    required: true
    description: 'Start of the commit range to check (can be a commit hash or a branch name).'
  to:
    required: false
    description: 'End of the commit range to check (can be a commit hash or branch).'
    default: HEAD
  working-directory:
    required: false
    description: 'Path to the root of the monorepo.'
    default: './'
  turbo-task-name:
    required: false
    description: 'Name of the turbo task to run.'
    default: 'build'
outputs:
  changed:
    description: 'True if the workspace changed, otherwise false.'
  affectedWorkspaces:
    description: 'List of workspaces that were changed and for which the task needed to be run.'
runs:
  using: 'node16'
  main: 'dist/index.js'
