name: 'example-push'
on: push

# IMPORTANT: You'll want to remove the defaults block and the working-directory on 2nd step.
# Check for the comments ;)

# You'll want to delete this "defaults" block in your workflow.
# This is to make sure that all run actions run in the example/yarn-workspaces directory.
defaults:
  run:
    working-directory: example/yarn-workspaces

jobs:
  example-build:
    runs-on: ubuntu-latest
    # You'll want to delete this "outputs" block in your workflow if you don't plan to use
    # the returned workspace names in a matrix job.
    # This makes the output of the action available to use for the matrix job.
    outputs:
      affectedWorkspaces: ${{ steps.changedAction.outputs.affectedWorkspaces }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: package-a changed in last commit?
        id: changedAction
        uses: Trampoline-CX/action-turbo-changed@v2
        with:
          workspace: package-a
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)
          working-directory: example/yarn-workspaces # You'll want to delete that on your end

      # Do something more meaningful here, like push to NPM, do heavy computing, etc.
      - name: Validate Action Output
        if: steps.changedAction.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: echo 'package-a changed!'

  # You'll want to delete this job if you don't plan to use the returned workspace names in a matrix job.
  build-affected:
    runs-on: ubuntu-latest
    needs: example-build
    strategy:
      matrix:
        workspace: ${{ needs.build.outputs.affectedWorkspaces }}
    steps:
      # Do something more meaningful here, like run tests, publish to npm
      - name: Dummy Build Step
        run: "echo 'Matrix run: ${{ matrix.workspace }} changed!'"
